# Site settings
author: Chris Carter
title: Power Programs
header-img: img/home-bg.png
email: chrisjohncarter123@gmail.com
copyright_name: Chris Carter
description: > # this means to ignore newlines until "baseurl:"
  Take a Journey into Deeper Programs
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chrisjohncarter123

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
